In [1]:
# python version
import sys
print(sys.executable)

C:\Users\felip\AppData\Local\Programs\Python\Python312\python.exe

In [2]:
import sys
import os
import pandas as pd
import numpy as np
import torch
import time

sys.path.append(os.path.abspath('../src'))

from sklearn.model_selection import train_test_split
from sklearn.base import clone
from DataLoader import DataLoader
from DataSplitter import DataSplitter
from PipelineBuilder import Pipeline
from CrossValidation import CrossValidation

In [3]:
# device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [4]:
# pytorch threads
n_threads = os.cpu_count()
torch.set_num_threads(n_threads)
n_threads

8

In [5]:
## Loading data
data_loader = DataLoader(path_train="../data/train.csv", path_eval="../data/validation.csv", path_test="../data/test.csv")
train, validation, test = data_loader.load()
train.shape, validation.shape, test.shape

((29000, 2), (1000, 2), (10000, 2))

In [6]:
## Splitting data
data_splitter = DataSplitter(src_language='english', target_language='portuguese')
X_train, y_train = data_splitter.split(train)
X_val, y_val = data_splitter.split(validation)
X_test, y_test = data_splitter.split(test)

## LSTM

In [7]:
# DL Pipeline 
params = {'model_name': "LSTM", 'tokenizer_method': "sentencepiece", 'vocab_size': 3000, 'max_length': 20, 'embedding_dim': 128, 'hidden_dim': 128, 
          'num_layers': 1, 'dropout': 0.3, 'teacher_forcing': 0.5, 'max_length_decoded': 20, 'lr': 1e-3, 'epochs': 1, 'batch_size': 128} 
params['device'] = "gpu"

pipeline = Pipeline(**params)
pipeline

Pipeline(batch_size=128, device='gpu', dropout=0.3, embedding_dim=128, epochs=1,
         hidden_dim=128, lr=0.001, max_length=20, max_length_decoded=20,
         num_layers=1, teacher_forcing=0.5, vocab_size=3000)

In [8]:
# Cross-Validation
cv = CrossValidation(pipeline=clone(pipeline))

# Holdout Validation
#cv_score = cv.evaluate_one_fold(X_train, y_train, X_test, y_test)
#print("Holdout Validation score: ", cv_score)

In [9]:
## Hyper-parameter tunning
cv = CrossValidation(pipeline=clone(pipeline))

param_grid = {
    'tokenizer_method': ["sentencepiece"],
    'max_length': [30],
    'vocab_size': [5000],
    'max_length_decoded': [30],
    'embedding_dim': [512], 
    'hidden_dim': [512], 
    'num_layers': [2],
    'teacher_forcing': [0.7], 
    'lr': [7e-4], 
    'epochs': [1], 
    'batch_size': [128]
}

cv_lstm_results, loss_curves, _ = cv.hyper_param_tune_one_fold(X_train, y_train, X_test, y_test, param_grid, 
                                                               reduced=True, train_size=10000, return_loss_curves=True)
cv_lstm_results

Time cleaning:  1.0369198322296143
SentencePiece
8.0641
[ 8. 12. 13. 17.]
SentencePiece
7.835
[ 7. 11. 13. 17.]
Time tokenizing:  1.972837209701538
Training Activated ? True
Loss after Epoch 1: 5.7937.
forward time: 13.47656429966446
backward time:  26.990855100215413
loss time:  0.5714516000589356
Loss after gradient descent: 5.793674.
Total Training time: 45.81423568725586.
Params:  {'batch_size': 128, 'embedding_dim': 512, 'epochs': 1, 'hidden_dim': 512, 'lr': 0.0007, 'max_length': 30, 'max_length_decoded': 30, 'num_layers': 2, 'teacher_forcing': 0.7, 'tokenizer_method': 'sentencepiece', 'vocab_size': 5000}
Fit time: 49.09048652648926
SentencePiece
8.3621
[ 8. 12. 14. 18.]
time cleaning and encoding test:  0.8178014755249023
Training Activated ? False
time predicting test:  12.305927991867065
Time decodig test:  0.06385993957519531
Prediction time: 13.187589406967163

Total CV time: 63.42158579826355

,batch_size,embedding_dim,epochs,hidden_dim,lr,max_length,max_length_decoded,num_layers,teacher_forcing,tokenizer_method,vocab_size,fit_time,pred_time,final_loss,final_validation_score,score
0,128,512,1,512,0.0007,30,30,2,0.7,sentencepiece,5000,49.090487,13.187589,5.793674,NaN,0.061827

In [10]:
cv.pipeline.set_params(epochs=150)
cv.pipeline.fit(X_train, y_train)
cv.pipeline.save("translatorLSTM2.pt")

Time cleaning:  3.066371202468872
SentencePiece
8.153413793103448
[ 8. 12. 13. 17.]
SentencePiece
7.920172413793104
[ 7. 12. 13. 17.]
Time tokenizing:  4.024739980697632
Training Activated ? True
Loss after Epoch 1: 5.2408.
Loss after Epoch 6: 2.8738.
Loss after Epoch 11: 1.8867.
Loss after Epoch 16: 1.2084.
Loss after Epoch 21: 0.7960.
Loss after Epoch 26: 0.5150.
Loss after Epoch 31: 0.3614.
Loss after Epoch 36: 0.2805.
Loss after Epoch 41: 0.2225.
Loss after Epoch 46: 0.1948.
Loss after Epoch 51: 0.1800.
Loss after Epoch 56: 0.1723.
Loss after Epoch 61: 0.1492.
Loss after Epoch 66: 0.1473.
Loss after Epoch 71: 0.1342.
Loss after Epoch 76: 0.1376.
Loss after Epoch 81: 0.1268.
Loss after Epoch 86: 0.1263.
Loss after Epoch 91: 0.1214.
Loss after Epoch 96: 0.1132.
Loss after Epoch 101: 0.1158.
Loss after Epoch 106: 0.1102.
Loss after Epoch 111: 0.1130.
Loss after Epoch 116: 0.1072.
Loss after Epoch 121: 0.1069.
Loss after Epoch 126: 0.1104.
Loss after Epoch 131: 0.1106.
Loss after Epoch 136: 0.1101.
Loss after Epoch 141: 0.1086.
Loss after Epoch 146: 0.1060.
forward time: 7049.570508590201
backward time:  12913.749409613549
loss time:  233.4923413892975
Loss after gradient descent: 0.105207.
Total Training time: 21219.04014992714.

In [11]:
cv.pipeline.score(X_test, y_test)

SentencePiece
8.2629
[ 8. 12. 14. 18.]
time cleaning and encoding test:  2.8828396797180176
Training Activated ? False
time predicting test:  13.982325315475464
Time decodig test:  0.27626466751098633

26.0218011350616

In [14]:
preds = cv.pipeline.predict(X_test)
preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0], 'translation': preds})
preds_df.tail(50)

SentencePiece
8.2629
[ 8. 12. 14. 18.]
time cleaning and encoding test:  0.885495662689209
Training Activated ? False
time predicting test:  12.2694673538208
Time decodig test:  0.08709025382995605

,english,portuguese,translation
9950,I have a lot of homework.,Eu tenho muito dever de casa.,Eu tenho muita lição de casa.
9951,This has to be stopped.,Isso tem que ser barrado.,Isso deve ser de.
9952,I do hope so.,Eu realmente espero.,Eu espero que pare.
9953,Tom doesn't like Mary very much.,Tom não gosta muito de Maria.,Tom não gosta muito de Maria.
9954,Are you worried about global warming?,Você está preocupado com o aquecimento global?,Você está preocupado com com pona?
9955,Tom is big and strong.,Tom é grande e forte.,Tom é pequeno e meu peixe.
9956,Tom can draw a perfect circle.,Tom sabe desenhar um círculo perfeito.,Tom pode ser um um jor de.
9957,These children are my grandchildren.,Estas crianças são meus netos.,Esses são meus são estão inidos.
9958,I don't like that part of town.,Não gosto daquela parte da cidade.,Eu não gosto daquele das minhas sorte.
9959,He led a life of luxury.,Ele levou uma vida de luxo.,Ele contgamente em fatos.
9960,Tom showed me his scar.,Tom me mostrou sua cicatriz.,Tom mostrou-me seu discurso.
9961,Tom died.,O Tom morreu.,Tom morreu.
9962,His designs are highly original.,Seus projetos são muito originais.,Os picadas do mundo é muito comprado.
9963,There is a lake in front of my house.,Há um lago em frente à minha casa.,Há em casa em frente- frente.
9964,We haven't started yet.,Nós ainda não começamos.,Nós ainda não voamos.
9965,I wish there were more men like Tom.,Gostaria que houvesse mais homens como Tom.,Queria que algumas pessoas mais parado no Tom.
9966,I don't think that Tom knows what time Mary is...,Eu não acho que Tom sabe quando Mary vai chega...,Eu acho que Tom não sabe que ninguém a escola ...
9967,Why would you want to hurt Tom?,Por que você iria querer machucar o Tom?,Por que você quer machucar o Tom?
9968,We're no longer children.,Nós não somos mais crianças.,não estamos mais crianças.
9969,I have a murder to solve.,Tenho um assassinato a resolver.,Tenho que meu próprio resolververam.
9970,I have a bomb.,Eu tenho uma bomba.,Eu tenho um atigaldor.
9971,I asked him for a favor.,Eu pedi a ele um favor.,Pedi para ele um favor.
9972,I told Tom to come early.,Eu disse para o Tom chegar cedo.,Eu disse para Tom não vir cedo.
9973,Tom knocked on Mary's office door.,Tom bateu na porta do escritório de Mary.,Tom bateu na Mary de primeiro com a.
9974,I love fishing.,Eu amo pescar.,Eu amo pescar.
9975,Do you suffer from insomnia?,Você sofre de insônia?,"Você sofrestio, saerz?"
9976,What's the meeting about?,Sobre o que é a reunião?,Qual é a reunião de falar?
9977,I didn't expect to see you at a place like this.,Eu não esperava encontrar-te num lugar como este.,Não esperava que você fosse outra vez um pouco.
9978,Tom says you're good at cooking.,Tom diz que você é bom em cozinhar.,O Tom pensa que você é uma boa cozinheira.
9979,I knew it.,Eu sabia.,Eu sabia.
9980,"I'm late, aren't I?","Estou atrasado, não estou?","Eu estou tarde, não sou?"
9981,I usually watch TV in the evening.,Geralmente assisto TV à noite.,Eu costumo assistir à noite.
9982,She said she needed to study French.,Ela disse que precisava estudar francês.,Ela disse que fala de francêssse.
9983,"What's going on with you, Tom?","O que está acontecendo com você, Tom?",O que está havendo com você?
9984,I know what Tom did.,Eu sei o que Tom fez.,Eu sei o que Tom fez.
9985,Take Tom and me there.,Leva Tom e a mim lá.,Tom e Mary me espera lá.
9986,My neighbor renovated her house completely.,Minha vizinha reformou completamente a casa dela.,Meu relógio pulasse uma vez em.
9987,Are you sure of it?,Você tem certeza disso?,Você tem certeza de que isso?
9988,Can you explain what this means?,Você pode me explicar o que isso significa?,Você pode explicar o que isso significa?
9989,Nobody knew my real name when I was in college.,Ninguém sabia meu nome verdadeiro quando eu es...,Ninguém sabia que meu nome era falando em meu ...
9990,Tom knows your secret.,Tom sabe o seu segredo.,Tom sabe seu plano.
9991,Tom put his hand over Mary's hand.,O Tom meteu a sua mão sobre a mão da Mary.,Tom colocou a mão dele pela Maria.
9992,We should be with Tom.,Nós deveríamos estar com o Tom.,Nós deveríamos estar com o Tom.
9993,I'm ready to leave this place.,Eu estou pronto para sair deste lugar.,Estou pronto para ir embora ao lugar.
9994,Tom clicked the checkbox.,Tom clicou na caixa de seleção.,Tom passou no prateleamento.
9995,Tom has money problems.,Tom tem problemas com dinheiro.,Tom tem dinheiro dinheiro.
9996,He had heard that his friend was dying.,Ele ouvira que seu amigo estava morrendo.,Ele tinha seu cachorro de fosse outra amigo.
9997,I'm sleeping.,Estou dormindo.,Estou dormindo.
9998,I'd like you to do your best.,Gostaria que você fizesse o seu melhor.,Eu gostaria que você iria o seu melhor.
9999,Aren't you finished yet?,Você ainda não terminou?,Você ainda não terminou?