In [1]:
# python version
import sys
print(sys.executable)

C:\Users\felip\AppData\Local\Programs\Python\Python312\python.exe

In [2]:
import sys
import os
import pandas as pd
import numpy as np
import torch
import time

sys.path.append(os.path.abspath('../src'))

from sklearn.model_selection import train_test_split
from sklearn.base import clone
from DataLoader import DataLoader
from DataSplitter import DataSplitter
from PipelineBuilder import Pipeline
from CrossValidation import CrossValidation

In [3]:
# device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [4]:
# pytorch threads
n_threads = os.cpu_count()
torch.set_num_threads(n_threads)
n_threads

8

In [5]:
## Loading data
data_loader = DataLoader(path_train="../data/train.csv", path_eval="../data/validation.csv", path_test="../data/test.csv")
train, validation, test = data_loader.load()
train.shape, validation.shape, test.shape

((29000, 2), (1000, 2), (10000, 2))

In [6]:
## Splitting data
data_splitter = DataSplitter(src_language='english', target_language='portuguese')
X_train, y_train = data_splitter.split(train)
X_val, y_val = data_splitter.split(validation)
X_test, y_test = data_splitter.split(test)

## LSTM

In [7]:
# DL Pipeline 
params = {'model_name': "LSTM", 'tokenizer_method': "sentencepiece", 'vocab_size': 3000, 'max_length': 20, 'embedding_dim': 128, 'hidden_dim': 128, 
          'num_layers': 1, 'dropout': 0.3, 'teacher_forcing': 0.5, 'max_length_decoded': 20, 'lr': 1e-3, 'epochs': 1, 'batch_size': 128} 
params['device'] = "gpu"

pipeline = Pipeline(**params)
pipeline

Pipeline(batch_size=128, device='gpu', dropout=0.3, embedding_dim=128, epochs=1,
         hidden_dim=128, lr=0.001, max_length=20, max_length_decoded=20,
         model_name='LSTM', num_layers=1, teacher_forcing=0.5, vocab_size=3000)

In [8]:
# Cross-Validation
cv = CrossValidation(pipeline=clone(pipeline))

# Holdout Validation
#cv_score = cv.evaluate_one_fold(X_train, y_train, X_test, y_test)
#print("Holdout Validation score: ", cv_score)

In [9]:
## Hyper-parameter tunning
cv = CrossValidation(pipeline=clone(pipeline))

param_grid = {
    'tokenizer_method': ["sentencepiece"],
    'max_length': [30],
    'vocab_size': [5000],
    'max_length_decoded': [30],
    'embedding_dim': [512], 
    'hidden_dim': [512], 
    'num_layers': [2],
    'teacher_forcing': [0.7], 
    'lr': [7e-4], 
    'epochs': [1], 
    'batch_size': [128]
}

#cv_lstm_results, loss_curves, _ = cv.hyper_param_tune_one_fold(X_train, y_train, X_test, y_test, param_grid, 
#                                                               reduced=True, train_size=10000, return_loss_curves=True)
#cv_lstm_results

In [10]:
#cv.pipeline.set_params(epochs=150)
#cv.pipeline.fit(X_train, y_train)
#cv.pipeline.save("translatorLSTM2.pt")

In [11]:
#cv.pipeline.score(X_test, y_test)

In [12]:
#preds = cv.pipeline.predict(X_test)
#preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0], 'translation': preds})
#preds_df.tail(50)

## Transformer (encoder-decoder)

In [13]:
# DL Pipeline 
params = {'model_name': "Transformer", 'tokenizer_method': "full words", 'vocab_size': 3000, 'max_length': 30, 'embedding_dim': 256, 
          'n_heads': 8, 'num_encoder_layers': 2, 'num_decoder_layers': 2, 'dim_feed_forward': 512, 'dropout': 0.1, 'max_length_decoded': 30, 
          'lr': 1e-3, 'epochs': 1, 'batch_size': 256} 
params['device'] = "gpu"

pipeline = Pipeline(**params)
pipeline

Pipeline(batch_size=256, device='gpu', dim_feed_forward=512, dropout=0.1,
         embedding_dim=256, epochs=1, lr=0.001, max_length=30,
         max_length_decoded=30, n_heads=8, tokenizer_method='full words',
         vocab_size=3000)

In [14]:
# Cross-Validation
cv = CrossValidation(pipeline=clone(pipeline))

# Holdout Validation
#cv_score = cv.evaluate_one_fold(X_train, y_train, X_test, y_test)
#print("Holdout Validation score: ", cv_score)

In [15]:
## Hyper-parameter tunning
cv = CrossValidation(pipeline=clone(pipeline))

param_grid = {
    'tokenizer_method': ["full words"],
    'max_length': [30],
    'max_length_decoded': [30],
    'vocab_size': [4000],
    'embedding_dim': [256],  
    'n_heads': [8],
    'num_encoder_layers': [4],
    'num_decoder_layers': [4],
    'dim_feed_forward': [1024],
    'dropout': [0.1],
    'lr': [5e-4], 
    'epochs': [1], 
    'batch_size': [128]
}

cv_trans_results, loss_curves, _ = cv.hyper_param_tune_one_fold(X_train, y_train, X_test, y_test, param_grid, 
                                                               reduced=True, train_size=10000, return_loss_curves=True)
cv_trans_results

Time cleaning:  1.585247278213501
vocab size: 2452.
Full Words
7.0669
[ 7. 10. 11. 15.]
vocab size: 3114.
Full Words
7.0661
[ 7. 10. 12. 15.]
Time tokenizing:  0.4105653762817383
Training Activated ? True
Loss after Epoch 1: 4.7306.
forward time: 12.997188200126402
backward time:  21.77096840098966
loss time:  0.39616900018882006
Loss after gradient descent: 4.730642.
Total Training time: 41.42674398422241.
Params:  {'batch_size': 128, 'dim_feed_forward': 1024, 'dropout': 0.1, 'embedding_dim': 256, 'epochs': 1, 'lr': 0.0005, 'max_length': 30, 'max_length_decoded': 30, 'n_heads': 8, 'num_decoder_layers': 4, 'num_encoder_layers': 4, 'tokenizer_method': 'full words', 'vocab_size': 4000}
Fit time: 43.75220251083374
Full Words
7.0843
[ 7. 10. 11. 15.]
time cleaning and encoding test:  0.9500818252563477
Training Activated ? False
time predicting test:  126.8571367263794
Time decodig test:  0.0352778434753418
Prediction time: 127.84249639511108

Total CV time: 173.67884612083435

,batch_size,dim_feed_forward,dropout,embedding_dim,epochs,lr,max_length,max_length_decoded,n_heads,num_decoder_layers,num_encoder_layers,tokenizer_method,vocab_size,fit_time,pred_time,final_loss,final_validation_score,score
0,128,1024,0.1,256,1,0.0005,30,30,8,4,4,full words,4000,43.752203,127.842496,4.730642,NaN,1.434746

In [16]:
#cv.pipeline.set_params(epochs=120)
#cv.pipeline.fit(X_train, y_train)
#cv.pipeline.save("translatorTransformer1.pt")

In [17]:
#cv.pipeline.score(X_test, y_test)

In [18]:
#preds = cv.pipeline.predict(X_test)
#preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0], 'translation': preds})
#preds_df.tail(50)

In [19]:
cv.pipeline.set_params(epochs=120, tokenizer_method="sentencepiece")
cv.pipeline.fit(X_train, y_train)
cv.pipeline.save("translatorTransformer2.pt")

Time cleaning:  5.214784145355225
SentencePiece
8.294206896551724
[ 8. 12. 13. 18.]
SentencePiece
8.151862068965517
[ 8. 12. 14. 18.]
Time tokenizing:  6.788647174835205
Training Activated ? True
Loss after Epoch 1: 4.6756.
Loss after Epoch 6: 1.7443.
Loss after Epoch 11: 0.9702.
Loss after Epoch 16: 0.6119.
Loss after Epoch 21: 0.4370.
Loss after Epoch 26: 0.3495.
Loss after Epoch 31: 0.2976.
Loss after Epoch 36: 0.2616.
Loss after Epoch 41: 0.2374.
Loss after Epoch 46: 0.2198.
Loss after Epoch 51: 0.2059.
Loss after Epoch 56: 0.1921.
Loss after Epoch 61: 0.1817.
Loss after Epoch 66: 0.1716.
Loss after Epoch 71: 0.1635.
Loss after Epoch 76: 0.1562.
Loss after Epoch 81: 0.1501.
Loss after Epoch 86: 0.1453.
Loss after Epoch 91: 0.1405.
Loss after Epoch 96: 0.1367.
Loss after Epoch 101: 0.1337.
Loss after Epoch 106: 0.1255.
Loss after Epoch 111: 0.1235.
Loss after Epoch 116: 0.1215.
forward time: 5074.172743302188
backward time:  9543.968869599514
loss time:  415.7167689919006
Loss after gradient descent: 0.117589.
Total Training time: 15745.201107025146.

In [20]:
cv.pipeline.score(X_test, y_test)

SentencePiece
8.3897
[ 8. 12. 14. 18.]
time cleaning and encoding test:  7.341774225234985
Training Activated ? False
time predicting test:  110.85435819625854
Time decodig test:  0.7064669132232666

35.935175450718326

In [21]:
preds = cv.pipeline.predict(X_test)
preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0], 'translation': preds})
preds_df.tail(50)

SentencePiece
8.3897
[ 8. 12. 14. 18.]
time cleaning and encoding test:  2.9923479557037354
Training Activated ? False
time predicting test:  93.90228319168091
Time decodig test:  0.6447384357452393

,english,portuguese,translation
9950,I have a lot of homework.,Eu tenho muito dever de casa.,Eu tenho muita lição de casa.
9951,This has to be stopped.,Isso tem que ser barrado.,Isso deve estar.
9952,I do hope so.,Eu realmente espero.,Assim espero.
9953,Tom doesn't like Mary very much.,Tom não gosta muito de Maria.,O Tom não gosta muito de a Mary.
9954,Are you worried about global warming?,Você está preocupado com o aquecimento global?,Você está preocupado com sono ou não?
9955,Tom is big and strong.,Tom é grande e forte.,Tom é grande e forte.
9956,Tom can draw a perfect circle.,Tom sabe desenhar um círculo perfeito.,Tom pode desenhar um crculo.
9957,These children are my grandchildren.,Estas crianças são meus netos.,Estes são meus filhos eletas.
9958,I don't like that part of town.,Não gosto daquela parte da cidade.,Eu não gosto da cidade.
9959,He led a life of luxury.,Ele levou uma vida de luxo.,Ele vçaria uma vida na vida.
9960,Tom showed me his scar.,Tom me mostrou sua cicatriz.,Tom me mostrou o lenço.
9961,Tom died.,O Tom morreu.,Tom morreu.
9962,His designs are highly original.,Seus projetos são muito originais.,Os geralços são altos.
9963,There is a lake in front of my house.,Há um lago em frente à minha casa.,Há um lago em frente a minha casa.
9964,We haven't started yet.,Nós ainda não começamos.,Nós ainda não começamos.
9965,I wish there were more men like Tom.,Gostaria que houvesse mais homens como Tom.,Eu queria que Tom fosse estar mais de verdade.
9966,I don't think that Tom knows what time Mary is...,Eu não acho que Tom sabe quando Mary vai chega...,Eu não acho que Tom sabe em que Mary vai chega...
9967,Why would you want to hurt Tom?,Por que você iria querer machucar o Tom?,Por que você quer machucar o Tom?
9968,We're no longer children.,Nós não somos mais crianças.,Não somos mais crianças.
9969,I have a murder to solve.,Tenho um assassinato a resolver.,Tenho que resolver um crime.
9970,I have a bomb.,Eu tenho uma bomba.,Eu tenho um bônica.
9971,I asked him for a favor.,Eu pedi a ele um favor.,Pedi a ele um favor.
9972,I told Tom to come early.,Eu disse para o Tom chegar cedo.,Eu disse ao Tom para vir cedo.
9973,Tom knocked on Mary's office door.,Tom bateu na porta do escritório de Mary.,Tom bateu na porta de Maria.
9974,I love fishing.,Eu amo pescar.,Eu adoro pescar.
9975,Do you suffer from insomnia?,Você sofre de insônia?,Você sofrer o sem da China?
9976,What's the meeting about?,Sobre o que é a reunião?,a reunião terminou?
9977,I didn't expect to see you at a place like this.,Eu não esperava encontrar-te num lugar como este.,Eu não esperava que te vi um lugar sobre isso.
9978,Tom says you're good at cooking.,Tom diz que você é bom em cozinhar.,Tom diz que você é uma boa cozinheira.
9979,I knew it.,Eu sabia.,Eu sabia que era.
9980,"I'm late, aren't I?","Estou atrasado, não estou?","Eu estou atrasado, né?"
9981,I usually watch TV in the evening.,Geralmente assisto TV à noite.,Eu costumo assistir à noite.
9982,She said she needed to study French.,Ela disse que precisava estudar francês.,Ela disse que precisava estudar francês.
9983,"What's going on with you, Tom?","O que está acontecendo com você, Tom?","O que está havendo com você, Tom?"
9984,I know what Tom did.,Eu sei o que Tom fez.,Eu sei o que Tom fez.
9985,Take Tom and me there.,Leva Tom e a mim lá.,Tom me Leve lá.
9986,My neighbor renovated her house completely.,Minha vizinha reformou completamente a casa dela.,Meu vizinho corveu a sua casa na performa.
9987,Are you sure of it?,Você tem certeza disso?,Vocês têm certeza disso?
9988,Can you explain what this means?,Você pode me explicar o que isso significa?,Você pode explicar o que isso significa?
9989,Nobody knew my real name when I was in college.,Ninguém sabia meu nome verdadeiro quando eu es...,Ninguém sabia quando eu estava na faculdade.
9990,Tom knows your secret.,Tom sabe o seu segredo.,Tom conhece o teu segredo.
9991,Tom put his hand over Mary's hand.,O Tom meteu a sua mão sobre a mão da Mary.,Tom colocou a mão de Mary.
9992,We should be with Tom.,Nós deveríamos estar com o Tom.,Nós deveríamos estar com o Tom.
9993,I'm ready to leave this place.,Eu estou pronto para sair deste lugar.,Estou pronto para partir.
9994,Tom clicked the checkbox.,Tom clicou na caixa de seleção.,Tom esferiu a caixa comifica.
9995,Tom has money problems.,Tom tem problemas com dinheiro.,Tom tem problemas problemas.
9996,He had heard that his friend was dying.,Ele ouvira que seu amigo estava morrendo.,Ele tinha ouvido falar disso.
9997,I'm sleeping.,Estou dormindo.,Estou dormindo.
9998,I'd like you to do your best.,Gostaria que você fizesse o seu melhor.,Gostaria de fazer o melhor possível para você.
9999,Aren't you finished yet?,Você ainda não terminou?,Você ainda não terminou?

In [22]:
preds_df.head(60)

,english,portuguese,translation
0,Everything matters.,Tudo importa.,Tudo está importa.
1,I'm going to get something to eat.,Vou comer qualquer coisa.,Vou pegar alguma coisa para comer.
2,Isn't there a pharmacy nearby?,Não há uma farmácia por aqui?,A próxima vez eu já não tem uma farsa?
3,The secret of longevity is to choose your pare...,Escolher os seus pais cuidadosamente é o segre...,A torre vai escolher sua falta com cuidado.
4,Tom isn't very likely to forget to do that.,Tom provavelmente não vai esquecer de fazer isso.,O Tom provavelmente não é muito provável que f...
5,They're both empty.,Ambos estão vazios.,Eles são vazio.
6,"We waited a long time, but Tom never came.",Nós esperamos por muito tempo mas o Tom nunca ...,"Nunca vimos tempo Tom, mas nunca apareceu."
7,They held the meeting here.,Eles fizeram a reunião aqui.,Eles prender a reunião aqui.
8,Are you ready to leave?,Você está pronto para partir?,Você está pronto para partir?
9,I heard Tom partied all night.,Ouvi Tom festejando a noite toda.,Eu ouvi Tom festejando a noite toda.
10,If you don't think the party is going to be an...,Se você não acha que a festa vai ser divertida...,Se você acha que o tempo vai conseguir ou não?
11,Tom walked into the bathroom.,Tom entrou no banheiro.,Tom entrou no banheiro.
12,Tom is at his desk eating a sandwich.,O Tom está na sua mesa comendo um sanduíche.,Tom está comendo uma escrivaninha no sanduíche.
13,Tom could tell by the smile on Mary's face tha...,Tom podia dizer pelo sorriso no rosto de Mary ...,Tom podia dizer a Mary que ela tinha uma festa...
14,All of my children go to school in Boston.,Todos os meus filhos estudam em Boston.,Todos os meus filhos dormem de Boston.
15,Tom said he thought I looked like I was bored.,Tom disse que achou que eu parecia entediado.,Eu disse que achava que o Tom estava entediado.
16,Tom likes playing chess.,Tom gosta de jogar xadrez.,Tom gosta de jogar xadrez.
17,He's cruel.,Ele é cruel.,Ele está caiando.
18,I'm rarely invited to parties.,Raramente sou convidado para festas.,Eu sou convidado a ter as festas.
19,He does not get up early.,Ele não acorda cedo.,Ele não se levanta cedo.
20,The first edition was published ten years ago.,A primeira edição foi publicada há dez anos.,A primeira vez foi publicado há dez anos.
21,We like it.,Nós gostamos disso.,Nós gostar disso.
22,Ask Tom where he parked his car.,Pergunte ao Tom onde ele estacionou o seu carro.,Pergunte ao Tom onde estacionou seu carro.
23,I haven't felt any pain so far.,Não senti nenhuma dor até o momento.,Eu não me senti tão dor.
24,Get out of here right away.,Saiam daqui imediatamente.,Fique fora daqui.
25,You're a father now.,Você é pai agora.,Tu és pai agora.
26,We've tried everything.,Nós tentamos tudo.,Existem tudo.
27,I've been having trouble waking up.,Tenho tido problemas para acordar.,Eu tenho tidoulado.
28,I don't know why he's not here today.,Eu não sei porque ele não está aqui hoje.,Não sei porque ele não está aqui hoje.
29,Tom can't play the piccolo.,Tom não sabe tocar flautim.,Tom não pode tocar carne que o piquenique.
30,"He still writes novels from time to time, but ...","Ele ainda escreve romances de vez em quando, m...",Ele frequentemente a pé para não tinha vez em ...
31,I'm not in good shape now.,Não estou em boa forma agora.,Não estou em boa forma agora.
32,Tom is going to ask Mary to do that for us.,O Tom vai pedir à Mary para fazer isto por nós.,Tom vai pedir a Mary para nós fazer isso.
33,You've been really good to me.,Você tem sido muito bom para mim.,Você tem me bom.
34,That's my favorite movie.,Esse é o meu filme favorito.,Esse é o meu filme histórinho favorito.
35,Tom and Mary are very old friends.,Tom e Mary são velhos amigos.,Tom e Maria são muito velhos.
36,We didn't know which bus to take.,Nós não sabíamos qual ônibus tomar.,Não sabíamos qual possudarmos.
37,They lost everything.,Eles perderam tudo.,Eles perdido tudo.
38,This pen doesn't work.,Esta caneta não funciona.,Esta caneta não funciona.
39,I should've not said anything.,Eu não deveria ter dito nada.,Eu devia não ter dito nada.
40,English is like a universal language.,O inglês é como uma língua universal.,Inglês é uma língua nativa.
41,The time will come when she'll regret it.,O tempo vai passar e ela vai se arrepender.,O tempo vai se lembrar quando ela vai se arrep...
42,She studied hard in order not to fail the entr...,Ela estudou muito para não falhar no teste de ...,Ela estudou muito para não ser reprovada no ex...
43,"Boys, as a rule, are taller than girls.","Garotos, por regra, são mais alto que garotas.","A Suíça, há uma pimenta anos."
44,I want to be cautious.,Quero ser cauteloso.,Eu quero serioso.
45,I bought a pen for your birthday present.,Comprei uma caneta de presente para o seu aniv...,Eu comprei uma caneta de aniversário.
46,He was sentenced to death.,Ele foi condenado à morte.,Ele foi condenado a morte.
47,What'll they do to Tom?,O que eles vão fazer com o Tom?,O que eles vão fazer com o Tom?
48,We had a little car trouble.,Nós tivemos um pequeno problema com o carro.,Tivemos um pouco de carro.
49,I would like to have this car repaired as soon...,Eu gostaria que esse carro fosse consertado o ...,Gostaria de provar tão ingregari quanto esse c...
50,Mom is older than Dad.,A mamãe é maior que o papai.,A motiva é mais velha do que o habitual.
51,Are you thinking about Tom?,O senhor está pensando no Tom?,Estáveis a pensar no Tom?
52,What is your date of birth?,Qual é sua data de nascimento?,Qual é sua data de nascimento?
53,Most people expected Tom to win.,A maioria das pessoas esperavam que Tom ganhasse.,A maioria das pessoas que o Tom esperava encon...
54,She's an individualist.,Ela é individualista.,Ela é uma anrita.
55,Tom wants to sit down.,Tom quer se sentar.,Tom quer se sentar.
56,I think Tom would like that.,Acho que o Tom gostaria disso.,Eu acho que o Tom gostaria de estar.
57,I expected the concert to last a little longer.,Esperava que o show durasse um pouco mais.,Eu esperava assistir ao concerto um pouco mais.
58,I'm sure I'll regret this.,Tenho certeza de que vou me arrepender disto.,Tenho certeza de que isto vai se arrepender.
59,Can you pick me up at the station?,Você pode me pegar na estação?,Você pode me buscar na estação?